#include "mps-gpx.h"                         // this project
/*----------------------------------------------------------------------------*/
// DATA
char sym_nam[256][32]=                       // symbol names
{
   "Anchor",
   "Bell",
   "Diamond, Green",
   "Diamond, Red",
   "Diver Down Flag 1",
   "Diver Down Flag 2",
   "Bank",
   "Fishing Area",
   "Gas Station",
   "Horn",
   "Residence",
   "Restaurant",
   "Light",
   "Bar",
   "Skull and Crossbones",
   "Square, Green",
   "Square, Red",
   "Buoy, White",
   "Waypoint",
   "Shipwreck",
   "Man Overboard",
   "Navaid, Amber",
   "Navaid, Black",
   "Navaid, Blue",
   "Navaid, Green",
   "Navaid, Green/Red",
   "Navaid, Green/White",
   "Navaid, Orange",
   "Navaid, Red",
   "Navaid, Red/Green",
   "Navaid, Red/White",
   "Navaid, Violet",
   "Navaid, White",
   "Navaid, White/Green",
   "Navaid, White/Red",
   "Dot, White",
   "Radio Beacon",
   "Boat Ramp",
   "Campground",
   "Restroom",
   "Shower",
   "Drinking Water",
   "Telephone",
   "Medical Facility",
   "Information",
   "Parking Area",
   "Park",
   "Picnic Area",
   "Scenic Area",
   "Skiing Area",
   "Swimming Area",
   "Dam",
   "Controlled Area",
   "Danger Area",
   "Restricted Area",
   "Ball Park",
   "Car",
   "Hunting Area",
   "Shopping Center",
   "Lodging",
   "Mine",
   "Trail Head",
   "Truck Stop",
   "Exit",
   "Flag",
   "Circle with X",
   "Mile Marker",
   "TracBack Point",
   "Golf Course",
   "City (Small)",
   "City (Medium)",
   "City (Large)",
   "City (Capitol)",
   "Amusement Park",
   "Bowling",
   "Car Rental",
   "Car Repair",
   "Fast Food",
   "Fitness Center",
   "Movie Theater",
   "Museum",
   "Pharmacy",
   "Pizza",
   "Post Office",
   "RV Park",
   "School",
   "Stadium",
   "Department Store",
   "Zoo",
   "Convenience Store",
   "Live Theater",
   "Scales",
   "Toll Booth",
   "Bridge",
   "Building",
   "Cemetery",
   "Church",
   "Civil",
   "Crossing",
   "Ghost Town",
   "Levee",
   "Military",
   "Oil Field",
   "Tunnel",
   "Beach",
   "Forest",
   "Summit",
   "Airport",
   "Heliport",
   "Private Field",
   "Soft Field",
   "Tall Tower",
   "Short Tower",
   "Glider Area",
   "Ultralight Area",
   "Parachute Area",
   "Seaplane Base",
   "Geocache",
   "Geocache Found",
   "Contact, Afro",
   "Contact, Alien",
   "Contact, Ball Cap",
   "Contact, Big Ears",
   "Contact, Biker",
   "Contact, Bug",
   "Contact, Cat",
   "Contact, Dog",
   "Contact, Dreadlocks",
   "Contact, Female1",
   "Contact, Female2",
   "Contact, Female3",
   "Contact, Goatee",
   "Contact, Kung-Fu",
   "Contact, Pig",
   "Contact, Pirate",
   "Contact, Ranger",
   "Contact, Smiley",
   "Contact, Spike",
   "Contact, Sumo",
   "Water Hydrant",
   "Flag, Red",
   "Flag, Blue",
   "Flag, Green",
   "Pin, Red",
   "Pin, Blue",
   "Pin, Green",
   "Block, Red",
   "Block, Blue",
   "Block, Green",
   "Bike Trail",
   "Fishing Hot Spot Facility",
   "Police Station",
   "Ski Resort",
   "Ice Skating",
   "Wrecker",
   "Anchor Prohibited",
   "Beacon",
   "Coast Guard",
   "Reef",
   "Weed Bed",
   "Dropoff",
   "Dock",
   "Marina",
   "Bait and Tackle",
   "Stump",
   "Circle, Red",
   "Circle, Green",
   "Circle, Blue",
   "Diamond, Blue",
   "Oval, Red",
   "Oval, Green",
   "Oval, Blue",
   "Rectangle, Red",
   "Rectangle, Green",
   "Rectangle, Blue",
   "Square, Blue",
   "Letter A, Blue",
   "Letter A, Green",
   "Letter A, Red",
   "Letter B, Blue",
   "Letter B, Green",
   "Letter B, Red",
   "Letter C, Blue",
   "Letter C, Green",
   "Letter C, Red",
   "Letter D, Blue",
   "Letter D, Green",
   "Letter D, Red",
   "Number 0, Blue",
   "Number 0, Green",
   "Number 0, Red",
   "Number 1, Blue",
   "Number 1, Green",
   "Number 1, Red",
   "Number 2, Blue",
   "Number 2, Green",
   "Number 2, Red",
   "Number 3, Blue",
   "Number 3, Green",
   "Number 3, Red",
   "Number 4, Blue",
   "Number 4, Green",
   "Number 4, Red",
   "Number 5, Blue",
   "Number 5, Green",
   "Number 5, Red",
   "Number 6, Blue",
   "Number 6, Green",
   "Number 6, Red",
   "Number 7, Blue",
   "Number 7, Green",
   "Number 7, Red",
   "Number 8, Blue",
   "Number 8, Green",
   "Number 8, Red",
   "Number 9, Blue",
   "Number 9, Green",
   "Number 9, Red",
   "Triangle, Blue",
   "Triangle, Green",
   "Triangle, Red",
   "Contact, Blonde",
   "Contact, Clown",
   "Contact, Glasses",
   "Contact, Panda",
   "Multi-Cache",
   "Letterbox Cache",
   "Puzzle Cache",
   "Library",
   "Bus Station",
   "City Hall",
   "Winery",
   "ATV",
   "Big Game",
   "Blind",
   "Blood Trail",
   "Cover",
   "Covey",
   "Food Source",
   "Furbearer",
   "Lodge",
   "Small Game",
   "Animal Tracks",
   "Treed Quarry",
   "Tree Stand",
   "Truck",
   "Upland Game",
   "Waterfowl",
   "Water Source",
   "unknown",
   "unknown",
   "unknown",
   "unknown",
   "unknown",
   "unknown",
   "unknown"
};
/*----------------------------------------------------------------------------*/
